name: Daily fetch tweets

on:
  schedule:
    - cron: '5 5 * * *'   # vsak dan ob 05:05 UTC (07:05 poleti v SLO)
  workflow_dispatch:       # omogoča ročni zagon v Actions

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Run fetch
        run: node scripts/fetch.mjs
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
